### ISSUE TITLE
Questions about ScreenshareCrack & VoiceChatMoveAll Plugins

### ISSUE THREAD

**Issue by BigFlubba** [discord-modifications/better-discord-plugins#15]
Can these plugins get you banned? Are these plugins spamming or affecting the API? Is [ScreenshareCrack](https://github.com/discord-modifications/better-discord-plugins/blob/master/ScreenshareCrack/ScreenshareCrack.plugin.js) just removing a limit in place locally on the client or . . . ?

**Comment by localip** [comment]
No, they are all safe to use.
