### ISSUE TITLE
CommandsAPI doesn't work

### ISSUE THREAD

**Issue by aauth** [discord-modifications/better-discord-plugins#16]
Title explains it, Discord updated the slash commands menu and it broke the CommandsAPI menu. Commands still work fine tho just no menu
![Screenshot from 2022-04-16 00-40-11](https://user-images.githubusercontent.com/67509680/163584391-64bf9510-41db-4ca7-b07e-e4c54f2dd144.png)

**Comment by aauth** [comment]
update: commands also cant reply lmao

**Comment by v6r** [comment]
bump

**Comment by GithubPremiumPlan** [comment]
this is still broken

**Comment by aauth** [comment]
update: it now doesn't work at all

**Comment by v6r** [comment]
@localip

**Comment by KeryWT** [comment]
Still not working I guess, unlucky

**Comment by adsdawdfawdcwacdaw** [comment]
So when is Eternal's funeral?
